// <auto-generated />
namespace ConsertoDeLivro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MudarComprimentoParaAltura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MudarComprimentoParaAltura));
        
        string IMigrationMetadata.Id
        {
            get { return "202105180044378_MudarComprimentoParaAltura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
